# Generated by Django 5.2.16 on 2026-07-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_cms', '0002_post_images_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='at_a_glance',
            field=models.JSONField(blank=True, default=list, help_text='Quick-facts card: list of {label, value}.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='comparison',
            field=models.JSONField(blank=True, default=dict, help_text='Comparison table: {heading, columns:[...], rows:[[...]]}; empty dict when none.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='how_it_works',
            field=models.TextField(blank=True, help_text='Mechanism/process prose (1-3 paragraphs). Empty for pure-definition terms.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='key_takeaways',
            field=models.JSONField(blank=True, default=list, help_text='3-5 skimmable TL;DR bullet strings shown near the top of the term page.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='EEAT citations: list of {label, url}.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='steps',
            field=models.JSONField(blank=True, default=list, help_text='Ordered process as a list of {title, detail}; renders as a visual stepper.'),
        ),
    ]
