# Generated by Django 5.2.14 on 2026-08-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_cms', '0005_tag_term_type_risk_band_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplan',
            name='scope_relevance',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'L1 · Core (build directly)'), (2, 'L2 · Strong (light angle)'), (3, 'L3 · Relevant (needs an angle)'), (4, 'L4 · Peripheral (shelf)'), (5, 'L5 · Fringe (shelf)')], db_index=True, help_text="Scope-relevance grade 1..5 (1=core in-scope, 5=fringe/off-scope). Levels 4-5 are shelved: excluded from the production/autopilot cycle and hidden from the default blog list until a scope expansion re-grades them. The per-level meaning is defined in the consumer's scope doc. NULL = ungraded.", null=True),
        ),
    ]
