# Generated by Django 5.2.14 on 2026-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_cms', '0006_contentplan_scope_relevance'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordClusterJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('label', models.CharField(help_text='Human name for the pool — usually the topic the keywords share.', max_length=255)),
                ('market', models.CharField(blank=True, help_text='Scaffold market slug the pool belongs to; blank means cross-market.', max_length=64)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('source_type', models.CharField(choices=[('search_console', 'Search Console'), ('keyword_research', 'Keyword Research Export'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('clustering', 'Clustering (claimed)'), ('clustered', 'Clustered'), ('failed', 'Failed'), ('skipped', "Skipped (won't cluster)")], db_index=True, default='queued', max_length=12)),
                ('priority', models.FloatField(blank=True, db_index=True, help_text='Summed demand across the pool — drains highest-demand pools first.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('prep_dir', models.CharField(blank=True, max_length=500)),
                ('spec_path', models.CharField(blank=True, max_length=500)),
                ('produced_plan_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword cluster job',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
