# Generated by Django 5.2.17 on 2026-08-17 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_cms', '0007_keywordclusterjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cluster_position',
            field=models.PositiveIntegerField(blank=True, help_text="This post's step in its topic_cluster's reading path (0 = pillar, 1..N = spokes in recommended reading order). Null when the post isn't in a cluster, or the cluster has no defined reading order yet. Powers next_in_path() / TopicCluster.ordered_posts().", null=True),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('cluster_position__isnull', False), ('topic_cluster__isnull', False)), fields=('topic_cluster', 'cluster_position'), name='blog_post_cluster_position_uniq'),
        ),
    ]
